# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Candidat.create(nom: 'Fulano', prenom: 'Juan', position: 1, bio: 'Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo. Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo.', bio_summary: 'Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo.', citation:'Il faut aider les Français de l‘étranger', photo:'https://tailwindcss.com/_next/static/media/kentcdodds.f2473a4e9577b345f55d0467a0a37ef5.jpg')
Candidat.create(nom: 'Fulanita', prenom: 'Juanita', position: 2, bio: 'Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo. Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo.', bio_summary: 'Lorem ipsum dolor sit amet. A aperiam omnis aut error alias qui corrupti voluptatem et fugit modi ea quasi maiores. At doloremque ullam et minima cupiditate et nihil laudantium aut vero nemo.', citation: 'Les Français de l‘étranger, notre priorité', photo:'https://tailwindcss.com/_next/static/media/debbie-obrien.fd2a06311039f2d0bf1828d36c209714.jpg')
Slogan.create(principal: "Avec un tel site, c‘est sûr qu'on gagne.", secondaire: "Il n‘y a qu‘une façon de convaincre l‘électorat et c‘est d‘utiliser des citations inspirantes placées au bon endroit.", image_homepage:"https://media.revistavanityfair.es/photos/60e85716b710ef1e877f8e62/master/w_1600,c_limit/31449.jpg")
Proposition.create(titre: "Un premier point de programme super", contenu:"Eos quia commodi hic mollitia cupiditate et ipsum illo et inventore illum et quaerat pariatur et tempora consequatur vel animi sunt. Et laudantium illo quae reiciendis est molestiae laborum aut neque aspernatur qui consequatur nobis ut saepe eaque. Eum nulla numquam non aliquam dolor id minima nisi in quae ipsa.")
Proposition.create(titre: "Un deuxième point de programme étonnant", contenu:"Eos quia commodi hic mollitia cupiditate et ipsum illo et inventore illum et quaerat pariatur et tempora consequatur vel animi sunt. Et laudantium illo quae reiciendis est molestiae laborum aut neque aspernatur qui consequatur nobis ut saepe eaque. Eum nulla numquam non aliquam dolor id minima nisi in quae ipsa.")
Proposition.create(titre: "Un troisième point de programme bluffant", contenu:"Eos quia commodi hic mollitia cupiditate et ipsum illo et inventore illum et quaerat pariatur et tempora consequatur vel animi sunt. Et laudantium illo quae reiciendis est molestiae laborum aut neque aspernatur qui consequatur nobis ut saepe eaque. Eum nulla numquam non aliquam dolor id minima nisi in quae ipsa.")
Proposition.create(titre: "Un dernier point de programme décoiffant", contenu:"Eos quia commodi hic mollitia cupiditate et ipsum illo et inventore illum et quaerat pariatur et tempora consequatur vel animi sunt. Et laudantium illo quae reiciendis est molestiae laborum aut neque aspernatur qui consequatur nobis ut saepe eaque. Eum nulla numquam non aliquam dolor id minima nisi in quae ipsa.")
Soutien.create(nom: "Jean-Baptiste Quelquechose", intitule: "Président du conseil régional de NA", citation: "Je laisse le soin à l‘ASFE de trouver la bonne formule qui me permettra de soutenir ce candidat.", photo:"https://picsum.photos/100")
Soutien.create(nom: "Jean-Baptiste Quelquechose", intitule: "Président du conseil régional de NA", citation: "Je laisse le soin à l‘ASFE de trouver la bonne formule qui me permettra de soutenir ce candidat.", photo:"https://picsum.photos/100")
Soutien.create(nom: "Jean-Baptiste Quelquechose", intitule: "Président du conseil régional de NA", citation: "Je laisse le soin à l‘ASFE de trouver la bonne formule qui me permettra de soutenir ce candidat.", photo:"https://picsum.photos/100")
Soutien.create(nom: "Jean-Baptiste Quelquechose", intitule: "Président du conseil régional de NA", citation: "Je laisse le soin à l‘ASFE de trouver la bonne formule qui me permettra de soutenir ce candidat.", photo:"https://picsum.photos/100")
Vote.create(titre:"Le vote des Français d‘Amerique du Nord", introduction:"Lorem ipsum dolor sit amet. Sed debitis veniam aut dolorem iusto ex autem deleniti ut suscipit velit ut provident sint ex maxime maxime. Eum quia mollitia et ipsum rerum et omnis expedita ut itaque dolorem aut veniam esse ut repellendus numquam. Et deserunt perspiciatis At soluta blanditiis qui esse doloribus aut earum enim et impedit laboriosam et necessitatibus veniam aut internos voluptate. Eum ipsum voluptas cum quod quasi et quia quidem in quasi amet.", contenu:"Lorem ipsum dolor sit amet. Sed debitis veniam aut dolorem iusto ex autem deleniti ut suscipit velit ut provident sint ex maxime maxime. Eum quia mollitia et ipsum rerum et omnis expedita ut itaque dolorem aut veniam esse ut repellendus numquam. Et deserunt perspiciatis At soluta blanditiis qui esse doloribus aut earum enim et impedit laboriosam et necessitatibus veniam aut internos voluptate. Eum ipsum voluptas cum quod quasi et quia quidem in quasi amet. Non dolores harum ut porro vitae et quis earum. Sit minima dolorem aut iusto recusandae qui obcaecati cumque. Non laudantium aspernatur et dolores enim aut perspiciatis voluptas qui molestiae necessitatibus. Sed nihil reprehenderit et architecto libero et pariatur officiis et neque expedita ut suscipit enim. Ut nulla nihil id accusamus perferendis sit enim laudantium qui ipsum repudiandae. Sit cupiditate ratione ad galisum quae est eveniet enim ut excepturi quis quo inventore fugit vel galisum dolore.")
Programme.create(titre:"Français à l’étranger, Français à part entière.", sous_titre:"Notre programme pour les Français d‘Amerique du Nord : des objectifs clairs et réalisables")
